image: docker:stable

stages:
  - build-docker

build-docker:
  stage: build-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/core/secchallenge-2022/web-1/instant-development-company:latest .
    - docker push $CI_REGISTRY/core/secchallenge-2022/web-1/instant-development-company:latest
